# Generated by Django 3.2.16 on 2022-12-27 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myschoolapp', '0003_teacherattendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherattendance',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='teacherattendance',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
