# Generated by Django 3.2.16 on 2022-12-29 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myschoolapp', '0004_auto_20221227_0728'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now=True)),
                ('studymaterial', models.FileField(upload_to='studymaterial')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myschoolapp.course')),
            ],
        ),
    ]
